version: "3.8"
services:
  # Granate web appplication
  granate_web_app:
    image: granate_web
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    restart: "always"

  # database service
  db:
    image: granate_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGPORT=${DB_PORT}
    build:
      context: database/
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: "always"

volumes:
  data:
